# Generated by Django 4.2.6 on 2026-01-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
